# Generated by Django 3.0.1 on 2020-05-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, default='post_photos/default.jpg', upload_to='post_photos/%d/%m/%Y')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
