# Generated by Django 3.0.1 on 2020-05-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('domain', models.CharField(help_text='Enter domains as comma separated values', max_length=300)),
                ('author', models.CharField(help_text='Name of person to contact', max_length=50)),
                ('phone', models.CharField(help_text='Enter 10-digit phone no.', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('prerequisites', models.TextField(help_text='Enter pre-requisites as comma separated values')),
                ('body', models.CharField(choices=[('Delta', 'Delta'), ('Spider', 'Spider'), ('DataByte', 'DataByte'), ('DC', 'Designer’s Consortium'), ('Builders’ Hive', 'Builders’ Hive'), ('3D', '3rd Dimension Aeromodelling Club'), ('RMI', 'RMI – Robotics and Machine Intelligence'), ('CSE', 'Computer Science & Engineering dept'), ('CIVIL', 'Civil Engineering dept'), ('CHEM', 'Chemical Engineering dept'), ('EEE', 'Electrical and Electronics Engineering dept'), ('ECE', 'Electronics and Communications Engineering dept'), ('ICE', 'Instrumentation & Control Eningeering dept'), ('MECH', 'Mechanical Engineering dept'), ('PROD', 'Production Eningeering dept'), ('META', 'Metallurgical Eningeering dept')], default='CSE', max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Not yet started'), (2, 'In progress'), (3, 'Completed')], default=1)),
                ('degree', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PhD', 'PhD'), ('All', 'All')], default='All', max_length=20)),
                ('duration', models.IntegerField(choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '5 months'), (6, '6 months'), (7, '>6 months')], default=6)),
                ('link', models.URLField(blank=True, help_text='Links if any')),
                ('required', models.PositiveSmallIntegerField(default=1, help_text='No. of people required')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
