# Generated by Django 3.0.3 on 2020-02-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('domain', models.CharField(help_text='Enter domains as comma separated values', max_length=300)),
                ('phone', models.CharField(help_text='Enter 10-digit phone no.', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('prerequisites', models.TextField(help_text='Enter pre-requisites as comma separated values')),
                ('author', models.CharField(help_text='Name of person to contact', max_length=50)),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
