# Generated by Django 3.0.3 on 2020-02-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='author',
        ),
    ]
