# Generated by Django 3.0.3 on 2020-02-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projects_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='author',
            field=models.CharField(default='Admin', help_text='Name of person to contact', max_length=50),
            preserve_default=False,
        ),
    ]
