# Generated by Django 3.0.3 on 2020-02-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='body',
            field=models.CharField(choices=[('Delta', 'Delta'), ('Spider', 'Spider'), ('DataByte', 'DataByte'), ('CSE', 'Computer Science & Engineering dept')], default='CSE', max_length=100),
        ),
    ]
