# Generated by Django 3.0.3 on 2020-02-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('1', 'Not yet started'), ('2', 'In progress'), ('3', 'Completed')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='body',
            field=models.CharField(choices=[('Delta', 'Delta'), ('Spider', 'Spider'), ('DataByte', 'DataByte'), ('CSE', 'Computer Science & Engineering dept'), ('CIVIL', 'Civil Engineering dept'), ('CHEM', 'Chemical Engineering dept'), ('EEE', 'Electrical and Electronics Engineering dept'), ('ECE', 'Electronics and Communications Engineering dept'), ('MECH', 'Mechanical Engineering dept')], default='CSE', max_length=100),
        ),
    ]
