# Generated by Django 3.0.3 on 2020-02-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200208_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='degree',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PhD', 'PhD'), ('All', 'All')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='body',
            field=models.CharField(choices=[('Delta', 'Delta'), ('Spider', 'Spider'), ('DataByte', 'DataByte'), ('DC', 'Designer’s Consortium'), ('Builders’ Hive', 'Builders’ Hive'), ('3D', '3rd Dimension Aeromodelling Club'), ('RMI', 'RMI – Robotics and Machine Intelligence'), ('CSE', 'Computer Science & Engineering dept'), ('CIVIL', 'Civil Engineering dept'), ('CHEM', 'Chemical Engineering dept'), ('EEE', 'Electrical and Electronics Engineering dept'), ('ECE', 'Electronics and Communications Engineering dept'), ('ICE', 'Instrumentation & Control Eningeering dept'), ('MECH', 'Mechanical Engineering dept'), ('PROD', 'Production Eningeering dept'), ('META', 'Metallurgical Eningeering dept')], default='CSE', max_length=100),
        ),
    ]
