# Generated by Django 3.0.3 on 2020-02-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projects_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='required',
            field=models.PositiveSmallIntegerField(default=1, help_text='No. of people required'),
        ),
    ]
