# Generated by Django 3.0.3 on 2020-02-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question')),
                ('answer', models.TextField(help_text='Answer')),
            ],
        ),
    ]
