# Generated by Django 3.0.3 on 2020-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='users_photo/default_user.jpg', upload_to='users_photo/default_user.jpg'),
        ),
    ]
