# Generated by Django 3.0.3 on 2020-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200208_1749'),
        ('users', '0003_user_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.projects'),
        ),
    ]
