# Generated by Django 3.0.3 on 2020-02-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(help_text='Enter your institute e-mail', max_length=254),
        ),
    ]
