# Generated by Django 3.0.3 on 2020-02-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200209_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='password',
            field=models.CharField(default='abc', help_text='Enter password', max_length=200),
            preserve_default=False,
        ),
    ]
