# Generated by Django 3.0.3 on 2020-02-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_professor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='photo',
            field=models.ImageField(default='users_photo/default_user.jpg', upload_to='users_photo/default_user.jpg'),
        ),
    ]
