# Generated by Django 3.0.3 on 2020-02-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of article', max_length=200)),
                ('description', models.CharField(help_text='Short description of article', max_length=300)),
                ('image', models.ImageField(default='help_photos/default_help.png', upload_to='help_photos')),
                ('link', models.URLField(help_text='Link to article')),
                ('author', models.CharField(help_text='Name of author', max_length=200)),
            ],
        ),
    ]
